version: '3.3'

services:

    bettingspree-nginx:
        depends_on: 
            - "bettingspree-interface"
        image: bragamann/bettingspree-nginx:2020-01-12
        container_name: bettingspree-nginx
        ports:
            - "80:80"
        networks:
            - backend


    bettingspree-interface:
        depends_on: 
            - "bettingspree-chat"
            - "bettingspree-bets"
            - "bettingspree-data"
        container_name: bettingspree-interface
        image: bragamann/bettingspree-interface:2020-01-12
        ports: 
            - "8080:8080"
        networks: 
            - backend


    bettingspree-chat:
        depends_on: 
            - "bettingspree-chatdb"
        container_name: bettingspree-chat
        image: bragamann/bettingspree-chat:2020-01-12
        ports: 
            - "4051:4051"
        networks: 
            - backend


    bettingspree-data:
        depends_on: 
            - "bettingspree-datadb"
        container_name: bettingspree-data
        image: bragamann/bettingspree-data:2020-01-12
        ports: 
            - "4052:4052"
        networks: 
            - backend
        volumes:
            - ./images:/app/public/images


    bettingspree-bets:
        depends_on: 
            - "bettingspree-betsdb"
        container_name: bettingspree-bets
        image: bragamann/bettingspree-bets:2020-01-12
        ports: 
            - "4053:4053"
        networks: 
            - backend


    bettingspree-manutencaodb:
        depends_on: 
            - "bettingspree-nginx"
        container_name: bettingspree-manutencaodb
        image: bragamann/bettingspree-manutencaodb:2020-01-12
        command: python ./__init__.py
        networks: 
            - backend


        









    bettingspree-chatdb:
        image: bragamann/bettingspree-chatdb:2020-01-12
        container_name: bettingspree-chatdb
        command: mongod --port 27018
        ports:
            - "27018:27018"
        networks:
            - backend
        volumes: 
            - mongodbchatvol:/data/db


    bettingspree-datadb:
        image: bragamann/bettingspree-datadb:2020-01-12
        container_name: bettingspree-datadb
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: PEI2020
        volumes:
           - mysqldatavol:/var/lib/mysql
           - ./dataDB/setup.sql:/docker-entrypoint-initdb.d/setup.sql


    bettingspree-betsdb:
        image: bragamann/bettingspree-betsdb:2020-01-12
        container_name: bettingspree-betsdb
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3307"
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: PEI2020
            MYSQL_TCP_PORT: 3307
        volumes:
           - mysqlbetsvol:/var/lib/mysql
           - ./betsDB/setup.sql:/docker-entrypoint-initdb.d/setup.sql
       


networks:
    backend:

volumes:
    mysqlbetsvol:
    mysqldatavol:
    mongodbchatvol: